server:
  port: 8096

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_bank_db
    #url: jdbc:mariadb://localhost:3306/book_bank_db
    #username: root
    #password: allthewayup
    username: aaron
    password: aaron
    #driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      show: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  http:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

file:
  upload:
    url: /home/bkaaron/Desktop/Live//
    #url: /volume1/bookbankapp//
    #url: ${UPLOAD_FOLDER}